In [ ]:
import pandas as pd
import numpy as np

In [ ]:
movies_df=pd.read_csv('/content/Movie.csv')
movies_df.head(20)

userId             movie  rating
0        3  Toy Story (1995)     4.0
1        6  Toy Story (1995)     5.0
2        8  Toy Story (1995)     4.0
3       10  Toy Story (1995)     4.0
4       11  Toy Story (1995)     4.5
5       12  Toy Story (1995)     4.0
6       13  Toy Story (1995)     4.0
7       14  Toy Story (1995)     4.5
8       16  Toy Story (1995)     3.0
9       19  Toy Story (1995)     5.0
10      22  Toy Story (1995)     3.0
11      23  Toy Story (1995)     4.0
12      24  Toy Story (1995)     4.0
13      31  Toy Story (1995)     3.0
14      34  Toy Story (1995)     5.0
15      39  Toy Story (1995)     5.0
16      47  Toy Story (1995)     1.0
17      53  Toy Story (1995)     4.0
18      54  Toy Story (1995)     4.0
19      58  Toy Story (1995)     5.0

In [ ]:
movies_df

userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

In [ ]:
movies_df.shape

(8992, 3)

In [ ]:
movies_df[(movies_df['userId']==24)]

userId                               movie  rating
12        24                    Toy Story (1995)     4.0
4548      24  Father of the Bride Part II (1995)     2.0
5212      24                         Heat (1995)     4.0
6469      24                      Sabrina (1995)     3.0
7449      24                    GoldenEye (1995)     3.0

In [ ]:
movies_df[(movies_df['userId']==6)]

userId                    movie  rating
1          6         Toy Story (1995)     5.0
3725       6  Grumpier Old Men (1995)     3.0
6464       6           Sabrina (1995)     5.0

In [ ]:
movies_df.sort_values('userId')

userId                    movie  rating
2569       1           Jumanji (1995)     3.5
3724       2  Grumpier Old Men (1995)     4.0
0          3         Toy Story (1995)     4.0
5204       4              Heat (1995)     3.0
7444       4         GoldenEye (1995)     4.0
...      ...                      ...     ...
6463    7117              Heat (1995)     5.0
2567    7119         Toy Story (1995)     5.0
2568    7120         Toy Story (1995)     4.5
3723    7120           Jumanji (1995)     4.0
7163    7120           Sabrina (1995)     4.0

[8992 rows x 3 columns]

In [ ]:
movies_df['movie'].unique()

array(['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)',
       'Waiting to Exhale (1995)', 'Father of the Bride Part II (1995)',
       'Heat (1995)', 'Sabrina (1995)', 'Tom and Huck (1995)',
       'Sudden Death (1995)', 'GoldenEye (1995)'], dtype=object)

In [ ]:
movies_df['movie'].value_counts()

movie
Toy Story (1995)                      2569
GoldenEye (1995)                      1548
Heat (1995)                           1260
Jumanji (1995)                        1155
Sabrina (1995)                         700
Grumpier Old Men (1995)                685
Father of the Bride Part II (1995)     657
Sudden Death (1995)                    202
Waiting to Exhale (1995)               138
Tom and Huck (1995)                     78
Name: count, dtype: int64

In [ ]:
movies_df.movie.unique()

array(['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)',
       'Waiting to Exhale (1995)', 'Father of the Bride Part II (1995)',
       'Heat (1995)', 'Sabrina (1995)', 'Tom and Huck (1995)',
       'Sudden Death (1995)', 'GoldenEye (1995)'], dtype=object)

In [ ]:
movies_df.userId.unique()

array([   3,    6,    8, ..., 7080, 7087, 7105])

In [ ]:
len(movies_df.userId.unique())

4081

In [ ]:
len(movies_df['userId'].unique())

4081

In [ ]:
movies_df['userId'].value_counts()

userId
903     10
1931    10
5881    10
156      9
1638     9
        ..
5697     1
5675     1
5664     1
5660     1
7105     1
Name: count, Length: 4081, dtype: int64

In [ ]:
movies_df['userId'].value_counts().shape[0]

4081

In [ ]:
movies_df['rating'].value_counts()

rating
3.0    2736
4.0    2660
5.0    1394
3.5     679
2.0     542
4.5     374
2.5     277
1.0     212
1.5      61
0.5      57
Name: count, dtype: int64

In [ ]:
movies_df['rating'].value_counts().shape[0]

10

In [ ]:
movies_df['rating'].unique()

array([4. , 5. , 4.5, 3. , 1. , 3.5, 1.5, 2. , 2.5, 0.5])

In [ ]:
len(movies_df['rating'].unique())

10

In [36]:
movies_df['movie'].value_counts()

movie
Toy Story (1995)                      2569
GoldenEye (1995)                      1548
Heat (1995)                           1260
Jumanji (1995)                        1155
Sabrina (1995)                         700
Grumpier Old Men (1995)                685
Father of the Bride Part II (1995)     657
Sudden Death (1995)                    202
Waiting to Exhale (1995)               138
Tom and Huck (1995)                     78
Name: count, dtype: int64

In [40]:
# change structure of datasets so that we can compute the similarity score
df=movies_df.pivot(index='userId',columns='movie',values='rating')
df

movie   Father of the Bride Part II (1995)  GoldenEye (1995)  \
userId                                                         
1                                      NaN               NaN   
2                                      NaN               NaN   
3                                      NaN               NaN   
4                                      NaN               4.0   
5                                      NaN               NaN   
...                                    ...               ...   
7115                                   4.0               NaN   
7116                                   3.5               NaN   
7117                                   NaN               3.0   
7119                                   NaN               NaN   
7120                                   NaN               NaN   

movie   Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
userId                                                                         
1                           NaN          NaN             3.5             NaN   
2                           4.0          NaN             NaN             NaN   
3                           NaN          NaN             NaN             NaN   
4                           NaN          3.0             NaN             NaN   
5                           NaN          NaN             3.0             NaN   
...                         ...          ...             ...             ...   
7115                        NaN          NaN             NaN             NaN   
7116                        NaN          NaN             NaN             NaN   
7117                        4.0          5.0             NaN             3.0   
7119                        NaN          NaN             NaN             NaN   
7120                        NaN          NaN             4.0             4.0   

movie   Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
userId                                                               
1                       NaN                  NaN               NaN   
2                       NaN                  NaN               NaN   
3                       NaN                  NaN               4.0   
4                       NaN                  NaN               NaN   
5                       NaN                  NaN               NaN   
...                     ...                  ...               ...   
7115                    NaN                  NaN               NaN   
7116                    NaN                  NaN               4.0   
7117                    1.0                  NaN               4.0   
7119                    NaN                  NaN               5.0   
7120                    NaN                  NaN               4.5   

movie   Waiting to Exhale (1995)  
userId                            
1                            NaN  
2                            NaN  
3                            NaN  
4                            NaN  
5                            NaN  
...                          ...  
7115                         NaN  
7116                         NaN  
7117                         NaN  
7119                         NaN  
7120                         NaN  

[4081 rows x 10 columns]

In [41]:
df.shape

(4081, 10)

In [43]:
df.fillna(0,inplace=True)
df

movie   Father of the Bride Part II (1995)  GoldenEye (1995)  \
userId                                                         
1                                      0.0               0.0   
2                                      0.0               0.0   
3                                      0.0               0.0   
4                                      0.0               4.0   
5                                      0.0               0.0   
...                                    ...               ...   
7115                                   4.0               0.0   
7116                                   3.5               0.0   
7117                                   0.0               3.0   
7119                                   0.0               0.0   
7120                                   0.0               0.0   

movie   Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
userId                                                                         
1                           0.0          0.0             3.5             0.0   
2                           4.0          0.0             0.0             0.0   
3                           0.0          0.0             0.0             0.0   
4                           0.0          3.0             0.0             0.0   
5                           0.0          0.0             3.0             0.0   
...                         ...          ...             ...             ...   
7115                        0.0          0.0             0.0             0.0   
7116                        0.0          0.0             0.0             0.0   
7117                        4.0          5.0             0.0             3.0   
7119                        0.0          0.0             0.0             0.0   
7120                        0.0          0.0             4.0             4.0   

movie   Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
userId                                                               
1                       0.0                  0.0               0.0   
2                       0.0                  0.0               0.0   
3                       0.0                  0.0               4.0   
4                       0.0                  0.0               0.0   
5                       0.0                  0.0               0.0   
...                     ...                  ...               ...   
7115                    0.0                  0.0               0.0   
7116                    0.0                  0.0               4.0   
7117                    1.0                  0.0               4.0   
7119                    0.0                  0.0               5.0   
7120                    0.0                  0.0               4.5   

movie   Waiting to Exhale (1995)  
userId                            
1                            0.0  
2                            0.0  
3                            0.0  
4                            0.0  
5                            0.0  
...                          ...  
7115                         0.0  
7116                         0.0  
7117                         0.0  
7119                         0.0  
7120                         0.0  

[4081 rows x 10 columns]

In [49]:
# Calculating Cosine Similarlity bw users
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [46]:
user_sim=1- pairwise_distances(df.values,metric='cosine')
user_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.55337157],
       [0.        , 1.        , 0.        , ..., 0.45883147, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       ...,
       [0.        , 0.45883147, 0.45883147, ..., 1.        , 0.45883147,
        0.47607054],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       [0.55337157, 0.        , 0.62254302, ..., 0.47607054, 0.62254302,
        1.        ]])

In [47]:
np.fill_diagonal(user_sim,0)

In [48]:
user_sim

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.55337157],
       [0.        , 0.        , 0.        , ..., 0.45883147, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.45883147, 1.        ,
        0.62254302],
       ...,
       [0.        , 0.45883147, 0.45883147, ..., 0.        , 0.45883147,
        0.47607054],
       [0.        , 0.        , 1.        , ..., 0.45883147, 0.        ,
        0.62254302],
       [0.55337157, 0.        , 0.62254302, ..., 0.47607054, 0.62254302,
        0.        ]])

In [50]:
user_sim=pd.DataFrame(user_sim)

In [51]:
user_sim

0         1         2         3         4         5         6     \
0     0.000000  0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
1     0.000000  0.000000  0.000000  0.000000  0.000000  0.390567  0.707107   
2     0.000000  0.000000  0.000000  0.000000  0.000000  0.650945  0.000000   
3     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4     1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
...        ...       ...       ...       ...       ...       ...       ...   
4076  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4077  0.000000  0.000000  0.752577  0.000000  0.000000  0.489886  0.000000   
4078  0.000000  0.458831  0.458831  0.619422  0.000000  0.701884  0.567775   
4079  0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
4080  0.553372  0.000000  0.622543  0.000000  0.553372  0.765455  0.391293   

          7         8         9     ...      4071      4072      4073  \
0     0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
1     0.615457  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
2     0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
3     0.615457  0.000000  0.388514  ...  0.800000  0.000000  0.000000   
4     0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
...        ...       ...       ...  ...       ...       ...       ...   
4076  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
4077  0.370543  0.752577  0.657870  ...  0.000000  0.752577  0.000000   
4078  0.889532  0.458831  0.568212  ...  0.344124  0.458831  0.000000   
4079  0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
4080  0.306519  0.622543  0.544201  ...  0.000000  0.622543  0.553372   

          4074      4075      4076      4077      4078      4079      4080  
0     0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
1     0.000000  0.000000  0.000000  0.000000  0.458831  0.000000  0.000000  
2     0.707107  0.000000  0.000000  0.752577  0.458831  1.000000  0.622543  
3     0.000000  0.989949  0.000000  0.000000  0.619422  0.000000  0.000000  
4     0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
...        ...       ...       ...       ...       ...       ...       ...  
4076  0.000000  0.000000  0.000000  0.658505  0.000000  0.000000  0.000000  
4077  0.532152  0.000000  0.658505  0.000000  0.345306  0.752577  0.468511  
4078  0.324443  0.648886  0.000000  0.345306  0.000000  0.458831  0.476071  
4079  0.707107  0.000000  0.000000  0.752577  0.458831  0.000000  0.622543  
4080  0.831497  0.000000  0.000000  0.468511  0.476071  0.622543  0.000000  

[4081 rows x 4081 columns]

In [55]:
user_sim.index=movies_df.userId.unique()
user_sim.columns=movies_df.userId.unique()
user_sim

3         6         8         10        11        12        13    \
3     0.000000  0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
6     0.000000  0.000000  0.000000  0.000000  0.000000  0.390567  0.707107   
8     0.000000  0.000000  0.000000  0.000000  0.000000  0.650945  0.000000   
10    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
11    1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
...        ...       ...       ...       ...       ...       ...       ...   
7044  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7070  0.000000  0.000000  0.752577  0.000000  0.000000  0.489886  0.000000   
7080  0.000000  0.458831  0.458831  0.619422  0.000000  0.701884  0.567775   
7087  0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
7105  0.553372  0.000000  0.622543  0.000000  0.553372  0.765455  0.391293   

          14        16        19    ...      6975      6979      6993  \
3     0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
6     0.615457  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
8     0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
10    0.615457  0.000000  0.388514  ...  0.800000  0.000000  0.000000   
11    0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
...        ...       ...       ...  ...       ...       ...       ...   
7044  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
7070  0.370543  0.752577  0.657870  ...  0.000000  0.752577  0.000000   
7080  0.889532  0.458831  0.568212  ...  0.344124  0.458831  0.000000   
7087  0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
7105  0.306519  0.622543  0.544201  ...  0.000000  0.622543  0.553372   

          7030      7031      7044      7070      7080      7087      7105  
3     0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
6     0.000000  0.000000  0.000000  0.000000  0.458831  0.000000  0.000000  
8     0.707107  0.000000  0.000000  0.752577  0.458831  1.000000  0.622543  
10    0.000000  0.989949  0.000000  0.000000  0.619422  0.000000  0.000000  
11    0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
...        ...       ...       ...       ...       ...       ...       ...  
7044  0.000000  0.000000  0.000000  0.658505  0.000000  0.000000  0.000000  
7070  0.532152  0.000000  0.658505  0.000000  0.345306  0.752577  0.468511  
7080  0.324443  0.648886  0.000000  0.345306  0.000000  0.458831  0.476071  
7087  0.707107  0.000000  0.000000  0.752577  0.458831  0.000000  0.622543  
7105  0.831497  0.000000  0.000000  0.468511  0.476071  0.622543  0.000000  

[4081 rows x 4081 columns]

In [57]:
user_sim.idxmax(axis=1) # axis=1 or columns

3         11
6        168
8         16
10      4047
11         3
        ... 
7044      80
7070    1808
7080     708
7087       8
7105    4110
Length: 4081, dtype: int64

In [58]:
user_sim.idxmax(axis=1)[0:10]

3       11
6      168
8       16
10    4047
11       3
12    6676
13    5953
14    4138
16       8
19    3603
dtype: int64

In [59]:
user_sim.iloc[0:5,0:5]

3    6    8    10   11
3   0.0  0.0  0.0  0.0  1.0
6   0.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0
11  1.0  0.0  0.0  0.0  0.0

In [62]:
movies_df[(movies_df['userId']==6) | (movies_df['userId']==168)]

userId                    movie  rating
1          6         Toy Story (1995)     5.0
60       168         Toy Story (1995)     4.5
3725       6  Grumpier Old Men (1995)     3.0
6464       6           Sabrina (1995)     5.0